/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tk_laomo_demo_jni_SquaredWrapper */

#ifndef _Included_tk_laomo_demo_jni_SquaredWrapper
#define _Included_tk_laomo_demo_jni_SquaredWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tk_laomo_demo_jni_SquaredWrapper
 * Method:    squared
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_tk_laomo_demo_jni_SquaredWrapper_squared
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
